### ISSUE TITLE
Enable PR checks on Bicep equivalent to the existing PR checks on the main branch

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#360]
**Benefit/Result/Outcome**  
So that Bicep parity is kept with Terraform for automatic PR checks.

**Description**
The current Terraform main branch has two PR checks: license/cla, and validate Terraform. The license/cla check should continue to function regardless of what is in the main branch. To keep parity with Terraform we should add an `az build` validate action. For example, the [Bicep Build](https://github.com/marketplace/actions/bicep-build) GitHub action implements a build action.

**Acceptance Criteria**
- A validate action for Bicep exists in `.github` folder. It can be `az build` or something similar that validates the Bicep code.

**Comment by glennmusa** [comment]
More information: https://github.com/Azure/bicep/blob/main/docs/cicd-with-bicep.md

We'd be doing everything up to L43-44 

```yaml
name: bicep build and deploy

on: push

env:
  # Common variables
  AZURE_RESOURCE_GROUP: 'myResourceGroupName'

jobs:
  bicep-build-and-deploy:
    name: bicep build and deploy
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Transpile bicep file into ARM template
      - name: Build ARM Template from bicep file
        run: |
          az bicep build --file ./main.bicep

      # Stop here if you only want to do "CI" which just generates the 
      # build artifact (ARM Template JSON)
```

and leaves a good starting point to take on #344 -- that'd be nice to have
